"""Main FastAPI application for Voice Detection API."""
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import uvicorn

from app.config import settings
from app.auth import verify_api_key
from app.models import VoiceDetectionRequest, VoiceDetectionResponse, ErrorResponse
from utils.audio_processor import AudioProcessor
from utils.feature_extractor import FeatureExtractor
from utils.classifier import VoiceClassifier

# Initialize FastAPI app
app = FastAPI(
    title="Voice Detection API",
    description="Language-agnostic AI voice detection using acoustic features",
    version="1.0.0"
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize components
audio_processor = AudioProcessor()
feature_extractor = FeatureExtractor()
classifier = VoiceClassifier()


@app.get("/")
async def root():
    """Root endpoint with API information."""
    return {
        "name": "Voice Detection API",
        "version": "1.0.0",
        "status": "operational",
        "endpoints": {
            "detection": "/api/voice-detection",
            "health": "/health"
        },
        "note": "API key required via 'x-api-key' header"
    }


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    model_trained = False
    try:
        if classifier.model is not None and hasattr(classifier.model, 'n_estimators'):
            # Check if model has been fitted
            model_trained = hasattr(classifier.model, 'estimators_') and len(classifier.model.estimators_) > 0
    except:
        model_trained = False
    
    return {
        "status": "healthy",
        "model_loaded": classifier.model is not None,
        "model_trained": model_trained
    }


@app.post(
    "/api/voice-detection",
    responses={
        401: {"description": "Missing API key"},
        403: {"description": "Invalid API key"},
        400: {"description": "Invalid request"},
        500: {"description": "Server error"}
    }
)
async def detect_voice(
    request: dict,
    api_key: str = Depends(verify_api_key)
):
    """
    Detect if a voice recording is AI-generated or human.
    
    This endpoint analyzes acoustic features of the audio to determine
    if it was generated by AI or spoken by a human. The analysis is
    language-agnostic and works across Tamil, Hindi, Telugu, Malayalam,
    English, and other languages.
    
    Args:
        request: Voice detection request with base64 encoded MP3
        api_key: Validated API key from header
        
    Returns:
        JSON response with classification, confidence, and explanation
    """
    try:
        # Step 1: Parse and validate request
        req = VoiceDetectionRequest.from_dict(request)
        
        # Step 2: Convert base64 to audio waveform
        waveform, sr = audio_processor.base64_to_audio(req.audio_base64)
        
        # Step 3: Extract acoustic features
        features = feature_extractor.extract_features(waveform, sr)
        
        # Step 4: Convert to feature vector
        feature_vector = feature_extractor.get_feature_vector(features)
        
        # Step 5: Classify
        classification, confidence, feature_importances = classifier.predict(feature_vector)
        
        # Step 6: Generate explanation
        explanation = classifier.generate_explanation(
            classification,
            confidence,
            features,
            feature_importances
        )
        
        # Step 7: Create and return response
        response = VoiceDetectionResponse(
            classification=classification,
            confidence=confidence,
            explanation=explanation
        )
        
        return response.to_dict()
        
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Internal server error: {str(e)}"
        )


@app.on_event("startup")
async def startup_event():
    """Run on application startup."""
    print("=" * 60)
    print("🎙️  Voice Detection API Starting...")
    print("=" * 60)
    print(f"API Key: {settings.get_api_key()}")
    print(f"Model Path: {settings.MODEL_PATH}")
    print(f"Sample Rate: {settings.SAMPLE_RATE} Hz")
    print("=" * 60)
    
    # Clean up old temp files
    audio_processor.cleanup_temp_files()


@app.on_event("shutdown")
async def shutdown_event():
    """Run on application shutdown."""
    print("\n🛑 Voice Detection API Shutting Down...")
    
    # Final cleanup
    audio_processor.cleanup_temp_files(max_age_hours=0)


if __name__ == "__main__":
    uvicorn.run(
        "app.main:app",
        host=settings.HOST,
        port=settings.PORT,
        reload=True
    )
